apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apps
  namespace: argocd
spec:
  sourceRepos:
    - {{ .Values.repo_url }}
  destinations:
    - namespace: 'argocd'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: 'argoproj.io'
      kind: 'Application'
    - group: 'networking.k8s.io'
      kind: 'Ingress'
