apiVersion: v1
kind: Secret
metadata:
  name: argocd-gitops
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
data:
  type: Z2l0
  url: {{ .Values.repo_url_encoded }}
  sshPrivateKey: {{ .Values.repo_private_key }}

