apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: standard-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: ${REPO_URL}
      revision: HEAD
      files:
      - path: apps/**.json
  template:
    metadata:
      name: '{{ .name }}'
      labels:
        argocd-image-updater.argoproj.io/write-back-method: git
        argocd-image-updater.argoproj.io/write-back-target: kustomization
        argocd-image-updater.argoproj.io/git-branch: main
        {{- range .containers }}
        argocd-image-updater.argoproj.io/image-list: {{ .id }}={{ .image }}
        argocd-image-updater.argoproj.io/{{ .id }}.update-strategy: {{ .strategy }}
        {{- end }}
    spec:
      project: default
      source:
        repoURL: ${REPO_URL}
        targetRevision: HEAD
        path: '{{ .path.path }}/{{ .dir }}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{ .namespace }}'
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          selfHeal: true
          prune: true
          allowEmpty: true
