apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ${SECRET_NAME}
spec:
  encryptedData:
    %{ for KEY, VALUE in SECRET_DATA ~}
    ${KEY}: ${VALUE}
    %{ endfor ~}
  template:
    type: ${SECRET_TYPE}
