on:
  repository_dispatch:
    types: create-sealed-secret

jobs:
  create-sealed-secret:
    name: Push Example File
    runs-on: ubuntu-latest
    steps:
      - name: Create file
        run: echo 'This is a test' > data.txt
      - name: Add file
        run: git add data.txt
      - name: Commit file
        run: git commit -m "Data.txt added"
      - name: Push file
        run: git push -u